import Head from "next/head"
import { FunctionComponent, memo } from "react"
import StarsBackground from "./StarsBackground"
import styles from '../styles/Home.module.css'
import Menu from "./Menu"

const App: FunctionComponent = () => {
	const MemoBackground = memo(StarsBackground)

	return <div className={styles.container}>
		<Head>
			<title>Francisco Elfers</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<MemoBackground />
		<Menu />
	</div>
}

export default App