import Head from "next/head"
import { FunctionComponent } from "react"
import StarsBackground from "./StarsBackground"
import styles from '../styles/Home.module.css'
import Menu, { MenuItems } from "./Menu"
import { useRouter } from "next/router"
import MenuItemDetail from "./MenuItemDetail"

const App: FunctionComponent = () => {
	const router = useRouter()

	return <div className={styles.container}>
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<StarsBackground />
		<Menu />
	</div>
}

export default App